spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/memoires_soutenance
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

server:
  port: 8080

logging:
  level:
    com.academique.memoires: DEBUG
    org.springframework.security: DEBUG